### PR TITLE
Add artifact evaluation committees from recent SE/PL conferences

### PR DESCRIPTION
**Pull request by jon-bell**
I found PC Miner to be very useful for building the PLDI AEC this year. This PR adds the dataset of AEC members for PLDI, POPL, ICFP, OOPSLA, FSE, ICSE and ISSTA.

I've been sitting on this for the past few months because I am not sure if it makes sense to make other UI changes, since it is unlikely that someone who wants to form a technical papers PC wants to see the AEC options (it was actually useful the other way around though, since it is easy to tell that someone who served on an AEC 3 years ago might be more likely to decline if they are serving on many PCs also).

### CODE REVIEW

**Comment by msridhar** [comment]
@jon-bell thanks for the contribution!  I am not sure about what kind of UI separation we want.  Can you post a screenshot of how the main UI looks with your changes?  I am a bit concerned about clutter with adding these new conferences.  The main thing would be to not reduce utility for PCMiner's main use case around choosing PC members.

**Comment by jon-bell** [comment]
It is somewhat unwieldy right now because all of the conferences are listed in a row:

Screenshot 2020-03-01 09 28 02

I think that the simplest fix would be to replace the single row listing all conferences (and their tick boxes) with instead one row for technical tracks and a row for artifact tracks (with a "check all"/"uncheck all" button for each), with the default to show all technical tracks and no artifacts, and the underlying implementation skipping loading the relevant files unless the event is checked. If this sounds reasonable, I can implement it and update this PR. I should also have mentioned that making this PR was motivated by other AEC chairs asking how we formed our PC and if they could use this too :)

**Comment by msridhar** [comment]
Your proposal sounds good to me. @franktip sound ok?

**Comment by franktip** [comment]
Yes, separate rows of checkboxes for PCs and AECs makes sense. Thanks for your contributions, Jon!

**Comment by jon-bell** [comment]
How does this look? Happy to keep tweaking, or if it looks good, I will update the PR.

Screenshot 2020-03-09 10 27 20

**Comment by msridhar** [comment]
Maybe we can put the top-level "Technical Tracks" and "Artifact Tracks" check boxes in their own rows?  So it looks like a bit of a heading with the specific tracks in the next row.  I think that would be a bit clearer.  Thanks @jon-bell!

**Comment by jon-bell** [comment]
Updated the PR, here's what it looks like now:
Screenshot 2020-03-11 11 05 25

**Comment by msridhar** [comment]
This looks great!  If you update the PR I will merge

**Comment by jon-bell** [comment]
Whoops, sorry - didn't realize I made the PR from my master branch. Pushed.

**Comment by msridhar** [comment]
Very sorry to drop the ball on merging this earlier.  But it's merged now!  Thanks again @jon-bell!

**Pull request merged**
