### PR TITLE
Update data for PLDI 2020-22

### PR DESCRIPTION
**Pull request by jnfoster**
Add the following:
* DBLP HTML for PLDI '20
* PC for PLDI '21
* DBLP HTML for PLDI '21
* PC for PLDI '22

### CODE REVIEW

**Comment by msridhar** [comment]
@jnfoster I merged the master branch into this PR.  Do you need to make any further changes now that #34 has landed?

**Comment by msridhar** [comment]
> The only lingering question I had: is it helpful / okay to preemptively populate the 2022 PC even though the papers and DBLP are not ready?

This is totally fine.  For anyone trying to form a PC now, this information will be useful.  Will merge, thanks again!

**Comment by msridhar** [comment]
FWIW, I _think_ our convention was to keep the `data.js` in the repo up to date, so someone cloning the repo can just open the UI.  (@franktip let me know if I'm wrong on that.)  Eventually we want to do a hosted version of PC-miner, at which point we won't need to do that anymore.

**Comment by franktip** [comment]
Yes, please make sure that the data.js file is up-to-date, so that people can use PC-miner without having to build anything

**Comment by jnfoster** [comment]
Sounds good. I'll make a new PR with an up-to-date `data.js`. (Just to confirm: `gradlew run` completing successfully will do that, right? I haven't manually checked that the output is correct.)

**Comment by msridhar** [comment]
No need, @jnfoster I already pushed an updated `data.js` to this PR

**Comment by jnfoster** [comment]
Whoops. I missed that. Thanks!

**Pull request merged**
